=== erolsptr/XML-Library-Management-System/API/Library.API/Library.API/members.dtd
<!ELEMENT LibraryMembers (Member*)>
<!ELEMENT Member (FirstName, LastName, MembershipDate, Email)>
<!ATTLIST Member ID CDATA #REQUIRED>

<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT MembershipDate (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

=== erolsptr/XML-Library-Management-System/API/Library.API/Library.API/members.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE LibraryMembers SYSTEM "members.dtd"[]>
<!-- Bu dosya kütüphane üyelerinin bilgilerini tutar. -->
<LibraryMembers>
  <Member ID="101">
    <FirstName>Alice</FirstName>
    <LastName>Wonderland</LastName>
    <MembershipDate>2023-01-15</MembershipDate>
    <Email>alice@example.com</Email>
  </Member>
  <Member ID="102">
    <FirstName>Bob</FirstName>
    <LastName>Builder</LastName>
    <MembershipDate>2023-02-20</MembershipDate>
    <Email>bob@example.com</Email>
  </Member>
  <Member ID="103">
    <FirstName>erol</FirstName>
    <LastName>saptir</LastName>
    <MembershipDate>2025-06-15</MembershipDate>
    <Email>wlşegmw@gmail.com</Email>
  </Member>
  <Member ID="104">
    <FirstName>Mehmetcan</FirstName>
    <LastName>Saptır</LastName>
    <MembershipDate>2025-06-24</MembershipDate>
    <Email>mcansaptir@gmail.com</Email>
  </Member>
</LibraryMembers>

=== erolsptr/XML-Library-Management-System/API/Library.API/Library.API/bin/Debug/net8.0/members.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LibraryMembers SYSTEM "members.dtd">
<!-- Bu dosya kütüphane üyelerinin bilgilerini tutar. -->
<LibraryMembers>
	<Member ID="101">
		<FirstName>Alice</FirstName>
		<LastName>Wonderland</LastName>
		<MembershipDate>2023-01-15</MembershipDate>
		<Email>alice@example.com</Email>
	</Member>
	<Member ID="102">
		<FirstName>Bob</FirstName>
		<LastName>Builder</LastName>
		<MembershipDate>2023-02-20</MembershipDate>
		<Email>bob@example.com</Email>
	</Member>
</LibraryMembers>
